vim.g.mapleader = " "
vim.g.background = "light"
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.number = true
vim.opt.relativenumber = false
vim.opt.signcolumn = "auto"
